import {useCallback,useEffect,useRef,useState} from 'react'
import {getDatabase,syncAfterDateSwitch,syncNow} from '../db'
import {beijingTime} from '../utils/exerciseDate'
import {projectV4Score} from '../utils/exerciseV4Score'
import type {ExercisePlanDefinition} from '@models/ExercisePlanSampleDataInitializer'
import type {ExerciseScoreSettlement} from '../types'
export type ExerciseState={status:number;completed_time?:string|null;note?:string|null;locked_at?:string|null;lock_reason?:string|null;earned_points?:number;max_points?:number;difficulty?:string;score_reason?:string|null;score_rule_version?:string;score_fact_status?:string}
type DietStatus='pending'|'completed'|'failed'
const dietPoints=(status:DietStatus)=>status==='completed'?5:0
const projectDietSettlement=(current:ExerciseScoreSettlement|null,date:string,previous:DietStatus,next:DietStatus):ExerciseScoreSettlement=>{
 const score=projectV4Score(current?.score_snapshot),earned=Math.max(0,Math.min(15,score.cats['饮食约束'].s-dietPoints(previous)+dietPoints(next)))
 const cats={...score.cats,'饮食约束':{s:earned,m:15}},total=Object.values(cats).reduce((sum,value)=>sum+value.s,0)
 return {...current,business_date:current?.business_date||date,plan_version:'v4',coin_amount:current?.coin_amount||0,score_total:total,score_snapshot:{total,cats,plan_version:'v4'},category_scores:JSON.stringify(cats)}
}
export function useExercise(date:string){
 const [log,setLog]=useState<any>(null),[settlement,setSettlement]=useState<ExerciseScoreSettlement|null>(null),[itemScores,setItemScores]=useState<Record<string,any>>({}),[checkins,setCheckins]=useState<Record<string,ExerciseState>>({}),[dietCheckins,setDietCheckins]=useState<Record<string,any>>({}),[deadlineFacts,setDeadlineFacts]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[weekNum,setWeek]=useState(1),[planVersion,setPlanVersionState]=useState('v0'),[planVersions,setPlanVersions]=useState<any[]>([]),[locked,setLocked]=useState(false),[planDefinition,setPlanDefinition]=useState<ExercisePlanDefinition|null>(null),[syncError,setSyncError]=useState<string|null>(null),[versionError,setVersionError]=useState<string|null>(null)
 const dietProjectionRef=useRef<Record<string,any>>({})
 const load=useCallback(async()=>{const db=await getDatabase(),version=db.getActiveExercisePlanVersion();db.discardInvalidV4DietCheckins(date,version);const definition=db.getExercisePlanDefinition(version),scores=Object.fromEntries(db.getExerciseItemScores(date,version).map((x:any)=>[x.item_key,x]));const loadedDiet=Object.fromEntries(db.getExerciseDietCheckins(date,version).map((x:any)=>[x.rule_key,x]));const projectionPrefix=`${date}:${version}:`;const projections=Object.entries(dietProjectionRef.current).filter(([key])=>key.startsWith(projectionPrefix));for(const [projectionKey,fact] of projections){const ruleKey=projectionKey.slice(projectionPrefix.length);const incoming=(loadedDiet as Record<string,any>)[ruleKey];if(!incoming||String(incoming.updated_at||'')<String(fact.updated_at||''))(loadedDiet as Record<string,any>)[ruleKey]=fact}setPlanVersionState(version);setPlanDefinition(definition);setPlanVersions(db.getExercisePlanVersions().filter((x:any)=>x.version!=='scoring-v3'));setLocked(db.isExerciseDateLocked(date));setLog(db.getExerciseDailyLog(date,version)||null);setSettlement(db.getExerciseSettlement(date,version)||null);setItemScores(scores);setDietCheckins(loadedDiet);setDeadlineFacts(db.getExerciseDeadlineFacts(date,version));setHistory(db.getExerciseDailyLogs(8,version));setWeek(db.getExerciseWeekNum());setCheckins(Object.fromEntries(db.getExerciseCheckins(date,version).map((x:any)=>{const score=scores[x.item_key];return [x.item_key,{status:Number(x.status),completed_time:x.completed_time,note:x.note,locked_at:x.locked_at,lock_reason:x.lock_reason,earned_points:score?.earned_points,max_points:score?.max_points,difficulty:score?.difficulty,score_reason:score?.score_reason,score_rule_version:score?.score_rule_version,score_fact_status:score?.status}]})));},[date])
 useEffect(()=>{dietProjectionRef.current={};setLog(null);setSettlement(null);setItemScores({});setCheckins({});setDietCheckins({});setDeadlineFacts([]);setLocked(false);setPlanDefinition(null)},[date])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{let cancelled=false;syncAfterDateSwitch('exercise',date).then(()=>{if(!cancelled)void load()}).catch(error=>console.warn('[useExercise] date switch sync failed:',error));return()=>{cancelled=true}},[date,load])
 const setState=useCallback(async(key:string,status:number,planItemId?:string,itemName?:string,completedTime?:string)=>{if(locked)return;const db=await getDatabase(),time=status===0?null:completedTime??beijingTime();db.toggleExerciseCheckin(date,key,status,undefined,time,planItemId,itemName,planVersion);setSyncError(null);setCheckins(p=>({...p,[key]:{...p[key],status,completed_time:time}}));try {const result=await syncNow({reason:'exercise-checkin'});if (!result.ok) {setSyncError(result.error||'exercise_checkin_sync_failed');return}await load()} catch (error) {setSyncError(error instanceof Error ? error.message : 'exercise_checkin_sync_failed')}},[date,locked,planVersion,load])
 const saveDay=useCallback(async(weight:number|undefined,day:string,done:number,total:number,score?:any,variant:'gym'|'rain'='gym',bodyFatRate?:number)=>{if(locked&&weight===undefined&&bodyFatRate===undefined)return;const db=await getDatabase();db.upsertExerciseDailyLog(date,weekNum,day,weight,done,total,planVersion,locked?undefined:score,variant,bodyFatRate);const result=await syncNow({reason:'exercise-body-metrics'});if(!result.ok)setSyncError(result.error||'exercise_body_sync_failed');await load()},[date,weekNum,load,locked,planVersion])
 const setDietState=useCallback((ruleKey:string,status:DietStatus)=>{if(locked||planVersion!=='v4')return;if(!planDefinition?.dietRulesValid||!ruleKey.trim()){setSyncError('exercise_diet_rule_config_invalid');return}const previous=(dietCheckins[ruleKey]?.status||'pending') as DietStatus,updatedAt=new Date().toISOString(),projectionKey=`${date}:${planVersion}:${ruleKey}`,fact={rule_key:ruleKey,plan_version:planVersion,date,status,occurred_at:status==='pending'?null:updatedAt,failure_reason:status==='failed'?'user_marked_failed':null,penalty_source_id:null,updated_at:updatedAt};dietProjectionRef.current[projectionKey]=fact;setSyncError(null);setDietCheckins(p=>({...p,[ruleKey]:{...p[ruleKey],...fact}}));setSettlement(current=>projectDietSettlement(current,date,previous,status));void(async()=>{try {const db=await getDatabase();db.toggleExerciseDietCheckin(date,ruleKey,status,planVersion);const result=await syncNow({reason:'exercise-diet-checkin'});if (!result.ok) {setSyncError(result.error||'exercise_diet_sync_failed');return}delete dietProjectionRef.current[projectionKey];await load()} catch (error) {setSyncError(error instanceof Error ? error.message : 'exercise_diet_sync_failed')}})()},[date,locked,planVersion,planDefinition,dietCheckins,load])
 const setVariant=useCallback(async(variant:'gym'|'rain')=>{const db=await getDatabase();db.setExerciseVariant(date,variant,planVersion);await load()},[date,load,planVersion])
 const resetDay=useCallback(async()=>{if(locked)return;(await getDatabase()).resetExerciseCheckins(date,planVersion);await load()},[date,load,locked,planVersion])
 const newWeek=useCallback(async()=>{const db=await getDatabase();db.resetExerciseCheckins(undefined,planVersion);db.setExerciseWeekNum(weekNum+1);await load()},[weekNum,load,planVersion])
 const setActivePlanVersion=useCallback(async(version:string)=>{try {const result=(await getDatabase()).setActiveExercisePlanVersion(version);if(!result.ok){setVersionError(result.error==='exercise_plan_version_incomplete'?`${version} 计划数据同步中，计划内容尚未完整。`:'切换运动版本失败，请重试。');return false}setVersionError(null);await load();return true}catch{setVersionError('切换运动版本失败，请重试。');return false}},[load])
 return{log,settlement,itemScores,checkins,dietCheckins,deadlineFacts,history,weekNum,planVersion,planVersions,planDefinition,locked,syncError,versionError,setActivePlanVersion,setState,setDietState,setVariant,saveDay,resetDay,newWeek}
}
