import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const assert = (value: unknown, message: string) => { if (!value) throw new Error(message) }
const read = (name: string) => readFileSync(fileURLToPath(new URL(name, import.meta.url)), 'utf8')
const hook = read('./useManagementPlanMindmap.ts')
const mindmap = read('../components/ManagementPlan/ManagementPlanMindmap.tsx')

assert(hook.includes("/api/management-plans/mindmap"), 'mindmap must read the server-owned snapshot')
assert(hook.includes("window.addEventListener('sync-pull-complete', schedule)"), 'mindmap must refresh after sync pull')
assert(hook.includes("window.addEventListener('management-plan-applied', schedule)"), 'mindmap must refresh after plan application')
assert(hook.includes("window.addEventListener('focus', schedule)"), 'mindmap must refresh when the app regains focus')
assert(hook.includes("document.addEventListener('visibilitychange', visible)"), 'mindmap must refresh when the document becomes visible')
assert(hook.includes('const seq = ++requestSeq.current'), 'mindmap refreshes must reject stale responses')
assert(hook.includes('timer = setTimeout(() => void refresh(), 150)'), 'bursty refresh signals must be debounced')
assert(hook.includes('projectManagementPlanMindmap'), 'snapshot must have a pure tree projection')
assert(hook.includes("id: 'management-plan'"), 'tree must start with the management plan root')
assert(hook.includes('items: item.items.map(product => ({ ...product }))'), 'tree projection must preserve product reward leaves')
assert(hook.includes('children: (item.children || []).map(projectItem)'), 'tree projection must preserve learning hierarchy')
assert(hook.includes('unboundProducts:'), 'tree projection must preserve unbound products without creating a domain')
assert(hook.includes('export function mindmapRewardFingerprint'), 'snapshot comparison must use a reusable reward fingerprint')
assert(hook.includes('context.productId'), 'product fingerprints must be matched by the stable product id')
assert(hook.includes('findItem(item.children || []'), 'coin fingerprints must find nested learning source items')
assert(mindmap.includes('当前数据库配置'), 'mindmap must distinguish current facts from version history')
assert(mindmap.includes("item.reward.status === 'unconfigured' ? '【金币】未配置'"), 'unconfigured reward must be explicit')
assert(!mindmap.includes('0.1'), 'mindmap must not contain a client-side reward fallback')
assert(mindmap.includes("product.source_status === 'source_missing' ? ' · 来源已不存在'"), 'missing product source must be explicit')
assert(mindmap.includes("if (!route || item.status === 'source_missing') return"), 'missing sources must not navigate')
assert(mindmap.includes('export interface MindmapNavigation'), 'reward leaves must publish a typed navigation intent')
assert(mindmap.includes("const route = product ? 'rewards' : routeFor[item.source_type]"), 'products must navigate to the reward page while coins retain their source page')
assert(mindmap.includes('returnContext: { sourceType: item.source_type, sourceId: item.source_id, productId: product?.id, fingerprint }'), 'bound rewards must retain their stable return context')
assert(mindmap.includes("returnContext: { sourceType: 'reward_item', sourceId: product.id, productId: product.id"), 'unbound products must retain their stable return context')
assert(!mindmap.includes("'/api/rewards/config'"), 'mindmap must not save task rewards directly')
assert(!mindmap.includes('await pullSync(true)'), 'mindmap must not run a local sync after navigation')
assert(mindmap.includes("import MindElixir, { type MindElixirData, type NodeObj } from 'mind-elixir'"), 'mindmap must use the maintained SVG mindmap engine')
assert(mindmap.includes("import 'mind-elixir/style.css'"), 'mindmap engine styles must be loaded')
assert(mindmap.includes("expanded: false,"), 'domains and learning groups must start collapsed')
assert(mindmap.includes("const isLearningGroup = item.source_type === 'learning_objective' || item.source_type === 'learning_kr'"), 'only Objective and KR remain collapsed after learning opens')
assert(mindmap.includes("expanded: children.length > 0 && !isLearningGroup"), 'ordinary execution items must expose reward leaves immediately')
assert(mindmap.includes("const MINDMAP_DOMAIN_ORDER = ['goal', 'sleep', 'learning_task', 'habit', 'checklist_task']"), 'mindmap must omit the exercise domain')
assert(!mindmap.includes("reward_item: '#6c9cc5'"), 'products must not render as a seventh top-level domain')
assert(mindmap.includes("direction: MindElixir.RIGHT"), 'engine layout must preserve the left-to-right parent branch direction')
assert(mindmap.includes('overflowHidden: true'), 'engine drag pan must remain disabled for stable expansion')
assert(mindmap.includes("mind.container.style.overflow = 'auto'"), 'long branches must use native scroll instead of clipping content')
assert(mindmap.includes("mind.container.style.touchAction = 'pan-x pan-y'"), 'touch devices must retain native two-axis scrolling')
assert(mindmap.includes('const startPanning = (event: PointerEvent)'), 'mindmap must start viewport panning from a pointer event')
assert(mindmap.includes('if (event.button !== 2) return'), 'only the right mouse button may pan the viewport')
assert(mindmap.includes('mind.container.scrollLeft = pan.left - (event.clientX - pan.x)'), 'right-drag must pan with the native horizontal scroll position')
assert(mindmap.includes('mind.container.scrollTop = pan.top - (event.clientY - pan.y)'), 'right-drag must pan with the native vertical scroll position')
assert(mindmap.includes("target.addEventListener('contextmenu', preventMapContextMenu)"), 'mindmap must suppress its context menu while panning')
assert(mindmap.includes("target.addEventListener('pointercancel', stopPanning, true)"), 'cancelled pointer input must stop panning')
assert(mindmap.includes("window.addEventListener('blur', stopPanning)"), 'losing focus must stop panning')
assert(mindmap.includes("const navigateByKeyboard = (event: KeyboardEvent)"), 'mindmap must support keyboard viewport navigation')
assert(mindmap.includes("event.key === 'Home'"), 'Home must return the view to the root node')
assert(mindmap.includes('onClick={focusRootNode}'), 'mindmap must provide a root-node navigation control')
assert(mindmap.includes('aria-label="回到根节点"'), 'root-node navigation control must be accessible')
assert(!mindmap.includes('mind.move('), 'viewport panning must not invoke the engine canvas move API')
assert(!mindmap.includes('mind.scale('), 'viewport panning must not invoke the engine canvas scale API')
assert(mindmap.includes("mind.bus.addListener('expandNode', keepExpandedNodeVisible)"), 'expanding a branch must preserve the visible node')
assert(mindmap.includes("element.scrollIntoView({ block: 'nearest', inline: 'nearest' })"), 'expanded node must use native viewport scrolling without moving the map')
assert(!mindmap.includes('mind.scaleFit()'), 'expansion must not rescale or drift the entire map')
assert(!mindmap.includes('toggleFromControl'), 'MindElixir must own exactly one expander event handler')
assert(mindmap.includes('const expandFromControl = (event: MouseEvent)'), 'expander must have an explicit click owner')
assert(!mindmap.includes("mind.container.addEventListener('pointerup'"), 'expander must not be toggled from a duplicate pointer handler')
assert(mindmap.includes('mind.expandNode(topic as Parameters<typeof mind.expandNode>[0])'), 'expander click must toggle exactly once')
assert(mindmap.includes("topic: item.reward.status === 'unconfigured' ? '【金币】未配置' : `【金币】+${item.reward.coins ?? 0} / -${item.reward.penalty ?? 0}`"), 'coin rewards must be concrete clickable leaves')
assert(mindmap.includes('topic: `【物品奖励】${product.icon || \'礼物\'} ${product.title}'), 'product rewards must be concrete clickable leaves')
assert(mindmap.includes("if (meta.kind === 'coins' && meta.item)"), 'coin leaf selection must open its edit action')
assert(mindmap.includes("else if (meta.kind === 'product' && meta.product)"), 'product leaf selection must open its edit action')
assert(mindmap.includes('const navigateFromTopic = (event: MouseEvent)'), 'every node click must be handled independently of selection state')
assert(mindmap.includes("eventTarget?.closest('me-tpc')"), 'click navigation must resolve the Mind Elixir topic element')
assert(mindmap.includes('handleSelection(topic.nodeObj)'), 'click navigation must reuse the existing reward routing logic')
assert(mindmap.includes("if (eventTarget?.closest('me-epd')) return"), 'expand controls must not trigger reward navigation')
assert(mindmap.includes("target.addEventListener('click', navigateFromTopic)"), 'topic clicks must install the direct navigation listener')
assert(!mindmap.includes("mind.bus.addListener('selectNodes'"), 'navigation must not depend on the one-time selection event')
assert(!mindmap.includes("'启用'"), 'mindmap must not invent an enabled status label')
assert(!mindmap.includes('function RoundedBranch('), 'hand-drawn branch geometry must be removed')

console.log('management plan mindmap contracts passed')
