import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const assert = (value: unknown, message: string) => { if (!value) throw new Error(message) }
const read = (name: string) => readFileSync(fileURLToPath(new URL(name, import.meta.url)), 'utf8')
const page = read('./LearningPage.tsx')
const hook = read('../../hooks/useLearning.ts')
const submission = read('../../hooks/useChecklistTaskSubmission.ts')

assert(hook.includes('categories.name AS category_name'), 'learning tasks must resolve the actual category name instead of assuming fixed category IDs')
assert(page.includes("task.category_name === '输入' || task.category_name === '输出'") && page.includes('tags: [category]'), 'valid learning tasks must add their actual input/output tag')
assert(page.includes('已加入清单') && page.includes('加入清单') && !page.includes('▶ 专注'), 'learning task controls must optimistically join the checklist and hide focus')
assert(page.includes('compactActionClass') && page.includes('✕ 删除') && page.includes('bg-red-600 text-white hover:bg-red-700'), 'checklist and delete actions must share compact geometry with a solid danger style')
assert(!page.includes('sourceType="learning_task"') && page.includes('sourceType="learning_objective"') && page.includes('SourceRewardEditor'), 'only objectives may expose the authoritative reward editor')
assert(page.includes('flex flex-wrap items-center') && page.includes('max-w-[calc(100vw-6rem)]'), 'task rewards and controls must wrap without overflowing narrow PC or Android layouts')
assert(page.includes('learningTaskId: task.id') && !page.includes('onConfirmed: () => { void setTaskStatus(task.id, 2) }'), 'joining a checklist links the task but does not complete it')
assert(page.includes("aria-label={isDone ? '标记为未完成' : '标记为已完成'}") && page.includes('onToggle={() => onToggleTask(task)}'), 'the checkbox must route through the checklist association workflow')
assert(!page.includes('分类无效，不能加入清单'), 'repaired learning tasks must not show the former invalid-category state')
assert(page.includes('<option value="输入">输入</option><option value="输出">输出</option>') && hook.includes('category_id: number'), 'manual learning tasks must choose input/output and send a real category id')
assert(!hook.includes("task.group_name || '输入'") && !hook.includes('task.category_id ?? categories'), 'learning imports must not silently default missing categories')
assert(submission.includes("operation: 'reconcile'") && submission.includes("else if (result.status === 'unknown') reconcile"), 'uncertain task submission must reconcile instead of repeatedly creating')
assert(submission.includes('onConfirmed?:') && submission.includes('confirmedKeys') && submission.includes('input.onConfirmed?.()'), 'only the first confirmed checklist result may notify the learning task')
assert(!/const failed[\s\S]{0,300}onConfirmed/.test(submission), 'failed checklist submissions must not mark learning tasks complete')
assert(hook.includes('cancelChecklistTask') && hook.includes('/api/learning/checklist-links/'), 'linked learning tasks must use the protected cancellation command')
assert(page.includes('const handleToggleTask = async') && page.includes('await cancelChecklistTask(task.id)'), 'checking an already linked learning task must cancel its checklist counterpart first')
assert(page.includes('handleAddChecklist(task)') && !page.includes('await toggleTask('), 'checkboxes must not use the ordinary learning task completion command')
assert(page.includes('createChecklistAttemptId()') && !page.includes('requestId: `learning-${task.id}-${dueDate}`'), 'each re-add attempt must use a fresh request id rather than reusing the calendar date')
assert(page.includes('clearChecklistTaskSubmission(`learning-${task.id}`)'), 'a successful cancellation must clear the prior checklist submission state')
assert(page.includes('setStatusOverride(task.id, 2)') && page.includes('setStatusOverride(task.id, 0)'), 'join and cancel must update the visible task status before their background operations finish')
assert(page.includes('onFailed: error =>') && page.includes('setStatusOverride(task.id)'), 'failed optimistic operations must restore the authoritative task display')
assert(page.includes('displayedCurrent') && page.includes('optimisticDelta'), 'KR progress must include the temporary task-status overlay')
assert(submission.includes('onFailed?:') && submission.includes('input.onFailed?.(reason)'), 'checklist creation exposes an explicit failure callback for UI recovery')
assert(submission.includes('confirmedKeys.current.has(input.requestId)') && submission.includes('submissionRequestIds'), 'confirmation deduplication must be scoped to the individual create attempt')
console.log('learning checklist contracts passed')
