import { memo, useState } from 'react'
import type { FlashCard, FlashClassificationLabel, FlashProcessingLog, FlashSkillChangeEvent, FlashSkillHistoryPage, FlashTaskRecommendation, TimeBookTimelineEntry } from '../../hooks/useTimeBook'
import type { ChecklistTaskSubmission } from '../../hooks/useChecklistTaskSubmission'

export const flashRecommendationsForCard = (items: FlashTaskRecommendation[], cardId: string) => items.filter(item => item.flash_card_id === cardId && !item.superseded_at)

export const isPureMoodFlash = (card: Pick<FlashCard, 'diary_content' | 'task_recommendations_json'>) => {
  if (!card.diary_content) return false
  try {
    const todos = JSON.parse(card.task_recommendations_json || '[]')
    return Array.isArray(todos) && todos.length === 0
  } catch { return false }
}

const FailureMark = () => <span aria-label="失败" className="flex h-5 w-5 items-center justify-center rounded bg-red-500 text-white"><svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"><line x1="5" y1="5" x2="19" y2="19" /><line x1="19" y1="5" x2="5" y2="19" /></svg></span>

const skillEventLabel = (event: FlashSkillChangeEvent) => ({ candidate_created: '生成候选', evaluated: '完成评估', activated: '已激活', failed: '未通过', rolled_back: '已回退' }[event.event_type] || event.event_type)

export const TimelinePointCard = memo(({ entry, items, taskSubmissions, onEdit, onDelete, onCreate, onIgnore, onClassify, onLoadLogs, onLoadSkillHistory }: { entry: TimeBookTimelineEntry; items: FlashTaskRecommendation[]; taskSubmissions: Record<string, ChecklistTaskSubmission>; onEdit: () => void; onDelete: () => void; onCreate: (item: FlashTaskRecommendation) => void; onIgnore: (item: FlashTaskRecommendation) => Promise<void>; onClassify: (cardId: string, label: FlashClassificationLabel) => Promise<void>; onLoadLogs: (id: string) => Promise<FlashProcessingLog[]>; onLoadSkillHistory: (cursor?: string | null) => Promise<FlashSkillHistoryPage> }) => {
  const [createError, setCreateError] = useState('')
  const [feedbackError, setFeedbackError] = useState('')
  const [feedbackLabel, setFeedbackLabel] = useState<FlashClassificationLabel | null>(null)
  const [logs, setLogs] = useState<FlashProcessingLog[] | null>(null)
  const [logError, setLogError] = useState('')
  const [skillEvents, setSkillEvents] = useState<FlashSkillChangeEvent[] | null>(null)
  const [skillCursor, setSkillCursor] = useState<string | null>(null)
  const [skillLoading, setSkillLoading] = useState(false)
  const [skillError, setSkillError] = useState('')
  if (entry.kind === 'checkin') {
    const sourcePalette = entry.checkinSource === 'habit' ? 'border-yellow-200 border-l-yellow-300 bg-yellow-50/90 dark:border-yellow-800 dark:border-l-yellow-700 dark:bg-yellow-950/35' : 'border-orange-200 border-l-orange-300 bg-orange-50/90 dark:border-orange-800 dark:border-l-orange-700 dark:bg-orange-950/35'
    return <article className={`flex w-full items-center gap-2 rounded-md border border-l-4 p-2.5 text-left shadow-sm ${sourcePalette}`}><time className="shrink-0 text-xs text-slate-500">{entry.at.slice(11, 16)}</time><div className="flex min-w-0 flex-1 items-center gap-1.5 text-sm text-slate-800 dark:text-slate-100"><span title={entry.checkinName} aria-label={entry.checkinName} className="min-w-0 flex-1 truncate">{entry.checkinName}</span><span className="shrink-0">{entry.checkinStatus === 'success' ? '✅' : <FailureMark />}</span></div></article>
  }
  if (entry.kind === 'diary') return <button type="button" onClick={() => document.getElementById(`timebook-${entry.diaryType}-diary`)?.scrollIntoView({ behavior: 'smooth', block: 'center' })} className="w-full rounded-md border border-amber-200 bg-amber-50/80 p-2.5 text-left shadow-sm dark:border-amber-900 dark:bg-amber-950/30"><span className="text-xs text-amber-700 dark:text-amber-200">{entry.at.slice(11, 16)} · {entry.diaryType === 'morning' ? '☀️ 晨间日记' : '🌙 晚间日记'}</span><p className="mt-1.5 whitespace-pre-wrap break-words text-sm leading-5 text-amber-950 dark:text-amber-50">{entry.diaryContent}</p></button>
  if (entry.kind !== 'flash') return null
  const card = entry.card
  const statusText = card.analysis_status === 'pending' ? '等待同步分析' : card.analysis_status === 'processing' ? 'AI 分析中' : card.analysis_status === 'failed' ? '分析失败 · AI 分析失败，请稍后重试' : card.analysis_status === 'done' ? '分析完成' : ''
  const itemsForCard = flashRecommendationsForCard(items, card.id)
  const pureMood = isPureMoodFlash(card)
  const loadLogs = async () => { setLogError(''); try { setLogs(await onLoadLogs(card.id)) } catch (cause: any) { setLogError(String(cause?.message || '处理日志读取失败')) } }
  const loadSkillHistory = async (reset = false) => { setSkillLoading(true); setSkillError(''); try { const page = await onLoadSkillHistory(reset ? null : skillCursor); setSkillEvents(previous => reset ? page.events : [...(previous || []), ...page.events]); setSkillCursor(page.next_cursor || null) } catch (cause: any) { setSkillError(String(cause?.message || 'Skill 演化记录读取失败')) } finally { setSkillLoading(false) } }
  const classify = async (label: FlashClassificationLabel) => { setFeedbackError(''); setFeedbackLabel(label); try { await onClassify(card.id, label) } catch (cause: any) { setFeedbackError(String(cause?.message || '提交反馈失败，请稍后重试')) } finally { setFeedbackLabel(null) } }
  const skillHistoryPanel = <details className="text-slate-600 dark:text-slate-300" onToggle={event => { if ((event.currentTarget as HTMLDetailsElement).open && skillEvents === null) void loadSkillHistory(true) }}><summary className="cursor-pointer">Skill 演化记录</summary>{skillLoading && skillEvents === null && <p className="mt-1.5">加载中…</p>}{skillError && <p className="mt-1.5 text-red-600">{skillError}</p>}{skillEvents?.length === 0 && <p className="mt-1.5">暂无演化记录</p>}{skillEvents?.map(event => <article key={event.id} className="mt-1.5 space-y-1 rounded border border-slate-200 p-2 dark:border-slate-700"><p>{event.created_at} · {skillEventLabel(event)}</p><p>版本：{event.version}{event.parent_version ? ` · 来源：${event.parent_version}` : ' · 初始版本'}</p><p>校准样本：分类 {event.sample_summary.classification || 0} · 润色 {event.sample_summary.polish || 0}</p>{event.rule_diff.added?.length ? <p>新增规则：{event.rule_diff.added.join('；')}</p> : null}{event.rule_diff.modified?.length ? <p>修改规则：{event.rule_diff.modified.map(item => `${item.from} → ${item.to}`).join('；')}</p> : null}{event.rule_diff.removed?.length ? <p>删除规则：{event.rule_diff.removed.join('；')}</p> : null}{event.evaluation_summary && <p>评估：{event.evaluation_summary}</p>}</article>)}{skillCursor && <button type="button" disabled={skillLoading} onClick={() => void loadSkillHistory()} className="mt-1.5 text-slate-500 hover:underline disabled:opacity-60">{skillLoading ? '加载中…' : '加载更多'}</button>}</details>
  return <article className={`w-full rounded-md border border-l-4 p-2.5 text-left shadow-sm ${pureMood ? 'border-rose-200 border-l-rose-300 bg-rose-50/90 dark:border-rose-900 dark:border-l-rose-800 dark:bg-rose-950/35' : 'border-sky-200 border-l-sky-300 bg-sky-50/90 dark:border-sky-800 dark:bg-sky-950/35'}`}><div className="flex items-start justify-between gap-3"><time className="text-xs text-slate-500">{entry.at.slice(11, 16)} · 闪念{statusText ? ` · ${statusText}` : ''}</time><div className="flex shrink-0 gap-2 text-xs"><button type="button" onClick={onEdit} className="text-slate-600 hover:underline dark:text-slate-300">{card.analysis_status === 'failed' ? '编辑并重试' : '编辑'}</button><button type="button" onClick={onDelete} className="text-red-600 hover:underline dark:text-red-300">删除</button></div></div>{!pureMood && <p className="mt-1 whitespace-pre-wrap break-words text-sm leading-5 text-slate-800 dark:text-slate-100">{card.polished_text || card.original_text}</p>}{pureMood && <section className="mt-1 text-sm text-rose-950 dark:text-rose-50">{card.diary_mood && <p className="font-medium">{card.diary_mood}</p>}<p className="whitespace-pre-wrap break-words leading-5">{card.polished_text || card.original_text}</p></section>}{!pureMood && itemsForCard.map(item => {
    const submission = taskSubmissions[`flash-${item.id}`]
    const autoJoined = item.status === 'added' && item.creation_mode === 'direct'
    const joined = item.status === 'added' || submission?.status === 'optimistic' || submission?.status === 'confirmed'
    return <div key={item.id} className={`mt-1.5 flex items-center justify-between gap-2 border-t border-slate-200 pt-1.5 text-xs dark:border-slate-700 ${item.status === 'pending' ? 'text-slate-700 dark:text-slate-200' : 'text-slate-400'}`}><span className={item.status === 'pending' ? '' : 'line-through'}>待办：{item.title}</span>{joined ? <span>{autoJoined ? '已自动加入' : '已加入清单'}</span> : item.status === 'ignored' ? <span>已忽略</span> : <span className="flex shrink-0 gap-2"><button type="button" onClick={() => onCreate(item)} className="rounded bg-blue-600 px-2 py-1 text-white">{submission?.status === 'failed' ? '加入失败 · 重试' : '加入清单'}</button><button type="button" onClick={() => void onIgnore(item).catch(cause => setCreateError(String(cause?.message || '忽略推荐任务失败')))} className="rounded border border-slate-300 px-2 py-1 text-slate-600 dark:border-slate-600 dark:text-slate-300">忽略</button></span>}</div>
  })}{!pureMood && createError && <p className="mt-1.5 text-xs text-red-600">{createError}</p>}{!pureMood && itemsForCard.some(item => taskSubmissions[`flash-${item.id}`]?.status === 'failed') && <p className="mt-1.5 text-xs text-red-600">{itemsForCard.map(item => taskSubmissions[`flash-${item.id}`]?.error).find(Boolean)}</p>}{!pureMood && card.diary_content && <section className="mt-2 rounded-md border border-rose-200 bg-rose-50/90 p-2.5 text-sm text-rose-950 dark:border-rose-900 dark:bg-rose-950/35 dark:text-rose-50">{card.diary_mood && <p className="font-medium">{card.diary_mood}</p>}<p className="whitespace-pre-wrap break-words leading-5">{card.diary_content}</p></section>}<div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 border-t border-slate-200 pt-1.5 text-xs dark:border-slate-700"><details className="text-slate-600 dark:text-slate-300" onToggle={event => { if ((event.currentTarget as HTMLDetailsElement).open && logs === null) void loadLogs() }}><summary className="cursor-pointer">详情</summary><p className="mt-1 whitespace-pre-wrap break-words">原文：{card.original_text}</p>{logs === null && !logError && <p className="mt-1.5">加载中…</p>}{logError && <p className="mt-1.5 text-red-600">{logError}</p>}{logs?.length === 0 && <p className="mt-1.5">暂无处理记录</p>}{logs?.map(log => <div key={log.id} className="mt-1.5 space-y-1 rounded border border-slate-200 p-2 dark:border-slate-700"><p>状态：{log.status}{log.error_code ? ` · ${log.error_code}` : ''}</p><p>开始：{log.started_at}{log.completed_at ? ` · 完成：${log.completed_at}` : ''}</p><p>提示词版本：{log.prompt_version}</p><details><summary className="cursor-pointer">查看输入、提示词与输出</summary><p className="mt-1 whitespace-pre-wrap break-words">输入：{log.input_text}</p><p className="mt-1 whitespace-pre-wrap break-words">提示词：{log.prompt_snapshot}</p>{log.raw_output && <p className="mt-1 whitespace-pre-wrap break-words">原始输出：{log.raw_output}</p>}{log.normalized_output && <p className="mt-1 whitespace-pre-wrap break-words">标准化输出：{log.normalized_output}</p>}</details></div>)}</details>{skillHistoryPanel}<button type="button" disabled={feedbackLabel !== null} onClick={() => void classify('todo')} className="text-slate-400 hover:text-slate-600 disabled:opacity-60 dark:text-slate-500 dark:hover:text-slate-300">{feedbackLabel === 'todo' ? '重新识别中…' : '这是待办'}</button><button type="button" disabled={feedbackLabel !== null} onClick={() => void classify('mood')} className="text-slate-400 hover:text-slate-600 disabled:opacity-60 dark:text-slate-500 dark:hover:text-slate-300">{feedbackLabel === 'mood' ? '重新识别中…' : '这是心情卡片'}</button></div>{feedbackError && <p className="mt-1.5 text-xs text-red-600">{feedbackError}</p>}</article>
})

TimelinePointCard.displayName = 'TimelinePointCard'
