import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { buildTimeBookTimeline, resolveExerciseCheckinName, type TimeBookTimelineEntry } from '../../hooks/useTimeBook'
import { flashRecommendationsForCard, isPureMoodFlash } from './TimelinePointCard'

const assert = (value: unknown, message: string) => { if (!value) throw new Error(message) }
const read = (name: string) => readFileSync(fileURLToPath(new URL(name, import.meta.url)), 'utf8')
const hook = read('../../hooks/useTimeBook.ts')
const submission = read('../../hooks/useChecklistTaskSubmission.ts')
const page = read('./TimeBookPage.tsx')
const timeline = read('./DualTrackTimeline.tsx')
const point = read('./TimelinePointCard.tsx')
const session = read('./TimelineSessionCard.tsx')
const app = read('../../App.tsx')
const prompt = read('../Timer/TimerAiPrompt.tsx')

assert(hook.includes('db.getFlashCards') && hook.includes('syncNow'), 'flash cards must reload from the shared sync cache')
assert(hook.includes("reason: 'server-change-followup'") && hook.includes('attempts >= 5') && hook.includes('processingFlashKey'), 'processing flash cards must use bounded server follow-up pulls')
assert(hook.includes("analysis_status: 'pending'"), 'local flash cards must enter the pending sync state')
assert(hook.includes('getFlashTaskRecommendations') && !hook.includes('JSON.parse(card.task_recommendations_json'), 'recommendations must read the server-owned local sync mirror, not reconstruct transient state')
const recommendationRows = [
  { id: 'rec-a', flash_card_id: 'flash-a', title: '洗澡', reason: '个人卫生', status: 'pending' as const },
  { id: 'rec-b', flash_card_id: 'flash-b', title: '买鸡蛋', reason: '购买', status: 'added' as const },
  { id: 'rec-c', flash_card_id: 'flash-c', title: '饭后洗澡', reason: '饭后行动', status: 'ignored' as const },
]
assert(flashRecommendationsForCard(recommendationRows, 'flash-a')[0]?.title === '洗澡', 'real flash_card_id rows must match their source card')
assert(flashRecommendationsForCard(recommendationRows, 'flash-b')[0]?.status === 'added', 'added recommendations must retain their mirrored state')
assert(flashRecommendationsForCard(recommendationRows, 'flash-c')[0]?.status === 'ignored', 'ignored recommendations must retain their mirrored state')
assert(!hook.includes('source_flash_id') && !point.includes('source_flash_id'), 'timebook must not rely on a nonexistent recommendation source alias')
assert(submission.includes('flash_recommendation_id') && hook.includes('flash-recommendations/${encodeURIComponent(recommendation.id)}/ignore'), 'recommendation actions must address one persistent recommendation')
assert(!hook.includes('dismissTaskRecommendations'), 'recommendations must not be globally dismissed')
assert(submission.includes('/api/ticktick/tasks/commands'), 'recommendation confirmation must reuse checklist task creation')
assert(submission.includes("operation: 'create'") && hook.includes('dueDate: formatBeijingDate()'), 'recommendation confirmation must create an all-day task due on Beijing today, not the viewed date')
assert(submission.includes("status: 'optimistic'") && submission.includes('retryDelays') && submission.includes("operation: 'reconcile'"), 'task submission must immediately render optimistically and only reconcile uncertain results')
assert(!point.includes('type="date"'), 'flash recommendations must not add a date picker before explicit confirmation')
assert(hook.includes('/api/timebook/flash-processing-logs'), 'timebook must load account-scoped flash processing logs')
assert(hook.includes('diary_mood?: string | null') && hook.includes('diary_content?: string | null'), 'flash cards must expose persisted mood diary fields')
assert(hook.includes('deleteFlashCard'), 'flash cards must expose the existing soft-delete command')
assert(point.includes('编辑并重试') && point.includes('AI 分析中') && point.includes('AI 分析失败，请稍后重试') && !point.includes('模型返回格式不完整'), 'processing and failed cards must remain visible, use the unified error, and remain retryable')
assert(page.includes('type="datetime-local"'), 'a flash card must expose its occurred time for editing')
assert(page.includes('原文（不可修改）') && page.includes('readOnly value={value.original_text}') && page.includes('润色后的内容'), 'flash editing must separate a read-only original from an editable polish')
assert(page.includes('corrected_text: polishedText') && page.includes('onSave={correctFlashPolish}') && !page.includes('original_text: text'), 'editing must save only the human-corrected polish, never rewrite the original')
assert(hook.includes('/polish-corrections') && hook.includes('request_id: requestId') && hook.includes("reason: 'flash-polish-correction'"), 'human polish must use the authoritative idempotent API and sync readback')
assert(point.includes('详情') && point.includes('原文：{card.original_text}'), 'polished flash cards must retain an original-text view inside details')
assert(point.includes('这是待办') && point.includes('这是心情卡片') && !point.includes("'反馈'"), 'flash cards must expose the two direct human classification actions beside details')
assert(point.includes('重新识别中…') && hook.includes('classification-feedback') && hook.includes("reason: 'flash-classification-feedback'"), 'classification feedback must report progress and refresh from server state')
assert(isPureMoodFlash({ diary_content: '我对乱改代码感到愤怒。', task_recommendations_json: '[]' } as any), 'a diary with no current todos must be a pure mood flash')
assert(!isPureMoodFlash({ diary_content: '有点烦。', task_recommendations_json: '[{"task":"提交报告"}]' } as any), 'a mixed todo and mood flash must not hide its todo')
assert(point.includes('pureMood') && point.includes('border-rose-200 border-l-rose-300 bg-rose-50/90') && point.includes('dark:bg-rose-950/35'), 'a pure mood flash must use one rose outer surface in both themes')
assert(point.includes('!pureMood && <p') && point.includes('!pureMood && card.diary_content'), 'pure mood flashes must omit the duplicate neutral body and nested mood surface')
assert((point.match(/card\.polished_text \|\| card\.original_text/g) || []).length >= 2, 'both regular and pure mood cards must render the confirmed polish with original fallback')
assert(!point.includes('{card.diary_content}</p></section>}{!pureMood && itemsForCard.map'), 'pure mood cards must never use model diary prose as their main body')
assert(point.includes('!pureMood && itemsForCard.map'), 'pure mood flashes must hide historical recommendation rows without deleting their persisted data')
assert(point.includes('原文：{card.original_text}') && point.includes('这是待办') && point.includes('这是心情卡片'), 'pure mood details and both direct classification actions must remain available')
assert(point.includes('superseded_at') && point.includes('!item.superseded_at'), 'reanalysis-withdrawn pending recommendations must not remain visible')
assert(!page.includes('AI 润色'), 'manual polish must not remain on flash-card controls')
assert(!page.includes('+ 记录'), 'timebook must not expose a second flash-card creation entry')
assert(!page.includes('AI 分析'), 'flash-card controls must not expose a manual analysis command')
assert(!page.includes('onOpenManagementPlanDraft'), 'flash cards must not open an overall management-plan draft')
assert(page.includes('ConfirmSheet'), 'flash-card deletion must use the shared confirmation sheet')
assert(!page.includes('TaskRecommendationSheet') && !page.includes('稍后处理'), 'recommendations must not open a dismissible sheet')
assert(hook.includes('buildTimeBookTimeline') && hook.includes('_diary_written_at'), 'timebook must project diaries by their saved writing time')
assert(page.includes('timebook-morning-diary') && page.includes('timebook-evening-diary'), 'the protected diary cards must remain the targets of timeline mirrors')
assert(page.includes('DualTrackTimeline') && timeline.includes('grid grid-cols-2') && timeline.includes('leftEntries') && timeline.includes('rightEntries'), 'timebook must keep independent dual tracks at narrow widths')
assert(hook.includes('const resetToToday') && hook.includes('if (selectedDate !== today) changeSelectedDate(today)') && app.includes("if (tab === 'timebook') timeBook.resetToToday()"), 'clicking timebook must return a historical selection to Beijing today without duplicating same-day sync')
assert(page.includes("useState<'asc' | 'desc'>('desc')") && page.includes('[...timelineEntries].reverse()') && page.includes('displayedTimelineEntries'), 'timeline order must default to descending and reverse a display copy only')
assert(page.includes('h-7 w-7') && page.includes('切换为最早在前') && page.includes('↕'), 'the sort control must align with the add button and expose its initial action')
assert(timeline.includes('before:left-1/2') && timeline.includes('space-y-1.5') && timeline.includes('rightEntries.map'), 'both tracks must share the center line without occupying each other\'s rows')
assert(point.includes("item.status === 'added'") && point.includes('line-through') && point.includes('已加入清单'), 'confirmed flash tasks must remain visible as completed within the session')
assert(point.includes("item.creation_mode === 'direct'") && point.includes('已自动加入'), 'direct recommendations must render as automatically added without a confirmation action')
assert(point.includes('加入失败 · 重试') && point.includes("submission?.status === 'failed'"), 'failed confirmation must remain visibly retryable')
assert(hook.includes("creation_mode?: 'direct' | 'confirm'") && hook.includes('local_task_id?: string | null'), 'the UI mirror must retain authoritative recommendation routing fields')
assert(point.includes("item.status === 'ignored'") && point.includes('忽略') && point.includes('已忽略') && point.includes('onIgnore'), 'pending recommendations must support persistent ignore')
assert(point.includes('处理日志') && point.includes('prompt_snapshot') && point.includes('normalized_output'), 'source flash cards must expose read-only processing logs')
assert(point.includes('Skill 演化记录') && point.includes('parent_version') && point.includes('sample_summary') && point.includes('evaluation_summary'), 'flash details must expose version lineage, sample counts, rule changes, and evaluation results')
assert(hook.includes('/api/timebook/flash-skill/history') && hook.includes('next_cursor'), 'skill history must use the account-scoped paginated API')
assert(point.includes('rounded-md border border-l-4 p-2.5') && point.includes('border-sky-200 border-l-sky-300 bg-sky-50/90') && point.includes('bg-amber-50/80'), 'flash cards must keep the compact scale while using their state-specific surface and diaries retain their treatment')
assert(point.includes('diary_content') && point.includes('bg-rose-50/90') && point.includes('border-rose-200') && point.includes('rounded-md') && point.includes('p-2.5') && point.includes('dark:bg-rose-950/35'), 'flash mood diaries must render as independent pale-pink cards in both themes, not pink text alone')
assert(point.includes('card.diary_mood') && point.includes('font-medium'), 'flash mood cards must display the persisted Chinese mood and emoji without adding a platform-specific field')
assert(point.includes('bg-sky-50/90') && point.includes('border-sky-200') && point.includes('dark:bg-sky-950/35'), 'the entire source flash card must use the sky surface palette')
assert(point.includes('bg-rose-50/90') && point.includes('border-rose-200') && point.includes('dark:bg-rose-950/35'), 'the mood card must keep its independent rose surface inside the sky flash card')
assert(!timeline.includes('时间点记录') && !timeline.includes('时间段记录'), 'dual-track timeline must not show redundant track titles')
assert(session.includes('formatDurationHms') && session.includes('CategoryIcon'), 'session cards must retain duration and category rendering')
assert(point.includes('rounded-md') && point.includes('p-2.5') && session.includes('rounded-md border border-l-4 p-2.5'), 'flash, diary, and session cards must share compact surfaces')
assert(prompt.includes('记录此刻闪念…'), 'the shared AI prompt must be relabeled for flash capture')
assert(prompt.includes('正在整理闪念…'), 'the shared AI prompt must report automatic polish progress')
assert(app.includes('onRecordFlashCard={timeBook.recordFlashCard}'), 'timer submission must create flash cards instead of management-plan drafts')

const checkins: TimeBookTimelineEntry[] = [
  { id: 'habit-success', at: '2026-08-14 22:30:00', kind: 'checkin', checkinSource: 'habit', checkinName: '刷牙', checkinStatus: 'success' },
  { id: 'exercise-failure', at: '2026-08-14 22:35:00', kind: 'checkin', checkinSource: 'exercise', checkinName: '深蹲', checkinStatus: 'failure' },
]
assert(buildTimeBookTimeline('2026-08-14', [], [], null, checkins).map(entry => entry.id).join(',') === 'habit-success,exercise-failure', 'checkin timeline entries must sort by their persisted time')
assert(hook.includes('habitEntries') && hook.includes('exerciseEntries') && hook.includes('completed_time'), 'timebook must map both persisted habit and exercise checkins')
assert(buildTimeBookTimeline('2026-08-14', [], [], null, [{ id: 'weight-overdue', at: '2026-08-14 09:00', kind: 'checkin', checkinSource: 'exercise', checkinName: '空腹称体重并记录', checkinStatus: 'failure' }]).at(-1)?.at === '2026-08-14 09:00', 'timebook must preserve the stored automatic failure time instead of replacing it with page-entry time')
assert(resolveExerciseCheckinName({ item_key: 'sc-2026-08-15-0', plan_version: 'v1' }, { getExercisePlanDefinition: () => ({ restSchedule: [{ item: '周末户外活动' }], sundayExtra: {} }), allRaw: () => [] }, '2026-08-15') === '周末户外活动', 'historical schedule checkins must resolve their readable plan item name')
assert(resolveExerciseCheckinName({ item_key: 'ex-2026-08-15-g-0', plan_item_id: 'plan-item' }, { allRaw: () => [{ name: '椭圆漫步机' }] }, '2026-08-15') === '椭圆漫步机', 'historical exercise plan items must resolve by their persisted plan item id')
assert(resolveExerciseCheckinName({ item_key: 'sc-2026-08-15-0' }, { allRaw: () => [] }, '2026-08-15') === '运动打卡项', 'unresolvable exercise checkins must never render their internal key')
assert(read('../Exercise/SchedulePanel.tsx').includes('undefined, r.item'), 'new schedule checkins must persist their readable item name')
assert(hook.includes("checkinSource: 'habit' as const"), 'habit checkins must retain their explicit timeline source')
assert(hook.includes("checkinSource: 'exercise' as const"), 'exercise checkins must retain their explicit timeline source')
assert(hook.includes('status === 2 || status === 1') && hook.includes('status === 1 || status === -1'), 'unchecked or reset checkins must be excluded from the timebook timeline')
assert(point.includes("entry.kind === 'checkin'") && point.includes('checkinName') && point.includes("'✅'") && point.includes('FailureMark'), 'left timeline cards must render success emoji and the shared red SVG failure mark')
assert(point.includes('title={entry.checkinName}') && point.includes('aria-label={entry.checkinName}') && point.includes('min-w-0 flex-1 truncate') && point.includes('shrink-0'), 'checkin names must truncate without hiding their full accessible name, time, or status marker')
assert(point.includes("entry.checkinSource === 'habit'"), 'checkin card styling must branch only on the explicit source')
assert(point.includes('bg-yellow-50/90') && point.includes('border-yellow-200') && point.includes('dark:bg-yellow-950/35'), 'habit checkin cards must use the yellow source palette')
assert(point.includes('bg-orange-50/90') && point.includes('border-orange-200') && point.includes('dark:bg-orange-950/35'), 'exercise checkin cards must use the orange source palette')
assert(timeline.includes("entry.kind === 'checkin'") && timeline.includes("entry.checkinStatus === 'success'"), 'checkin dots must keep success and failure states distinct')

console.log('timebook flash card contracts passed')
