import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const assert = (value: unknown, message: string) => { if (!value) throw new Error(message) }
const read = (name: string) => readFileSync(fileURLToPath(new URL(name, import.meta.url)), 'utf8')
const sheet = read('./ManagementPlanSheet.tsx')
const history = read('./ManagementPlanHistory.tsx')
const app = read('../../App.tsx')
const prompt = read('../Timer/TimerAiPrompt.tsx')
const hook = read('../../hooks/useManagementPlan.ts')

assert(app.includes("setManagementPlanMode('history')"), 'top action must enter history mode')
assert(app.includes('onOpenManagementPlanHistory={openManagementPlanHistory}'), 'top action must receive the history callback')
assert(prompt.includes('onSubmit(requestText)'), 'homepage prompt must submit a draft request')
assert(sheet.includes("mode = 'draft'"), 'plan sheet must support a draft mode')
assert(sheet.includes("if (mode !== 'draft') return"), 'history mode must not generate a draft from initial text')
assert(sheet.includes('<ManagementPlanHistory runtime={runtime}'), 'history mode must show the version list')
assert(sheet.includes('生成整体方案'), 'history mode must provide the overall-plan generation command')
assert(sheet.includes('versions.exportRevision(revision.id)'), 'history mode must read selected version content')
assert(sheet.includes('<ManagementPlanMindmap runtime={runtime}'), 'history entry must expose the current mindmap')
assert(sheet.includes('onNavigate?: (intent: MindmapNavigation) => void'), 'sheet must forward typed mindmap navigation intent')
assert(sheet.includes('onNavigate={intent => { onNavigate?.(intent); onClose() }}'), 'sheet must close after forwarding the mindmap navigation intent')
assert(sheet.includes("useState<'mindmap' | 'versions'>('mindmap')"), 'history entry must default to the current mindmap')
assert(sheet.includes('当前数据库配置与奖励关系'), 'mindmap mode must identify current database facts')
assert(sheet.includes('已发布方案版本历史'), 'version mode must identify historical information')
assert(sheet.includes('const [isFullscreen, setIsFullscreen] = useState(false)'), 'plan sheet must track its fullscreen state')
assert(sheet.includes("document.addEventListener('fullscreenchange'"), 'Escape must synchronize through the native fullscreen event')
assert(sheet.includes('requestFullscreen()'), 'fullscreen control must request native fullscreen')
assert(sheet.includes('document.exitFullscreen()'), 'fullscreen control must exit native fullscreen')
assert(sheet.includes("h-[100dvh] max-h-none max-w-none rounded-none"), 'fullscreen mode must occupy the full viewport')
assert(sheet.includes("aria-label={isFullscreen ? '退出全屏' : '全屏'}"), 'fullscreen control must have an accessible stateful label')
assert(sheet.includes("const isReview = draftMode === 'review'"), 'plan sheet must distinguish review mode')
assert(sheet.includes("'总结当前方案，只读不应用'"), 'review mode must explain that it is read-only')
assert(sheet.includes('const evidence = plan.draft?.payload?.review?.evidence'), 'review mode must read server-owned evidence')
assert(sheet.includes('aria-label="金币规则"'), 'review mode must expose coin rules before analysis')
assert(sheet.includes('完成 +{rule.coins} / 失败 -{rule.penalty} 金币'), 'review mode must render exact coin values')
assert(sheet.includes('aria-label="商品奖励"'), 'review mode must expose store rewards before analysis')
assert(sheet.includes('累计 ${item.required_count} 次'), 'review mode must render unlock thresholds')
assert(sheet.includes('来源已不存在'), 'review mode must disclose missing sources')
assert(sheet.includes('plan.draft?.payload?.review?.strengths'), 'review mode must render strengths')
assert(sheet.includes("'校验变更'"), 'proposal mode must expose explicit validation before apply')
assert(sheet.includes('草案不含可执行项目，请重新生成方案。'), 'empty drafts must not look applicable')
assert(sheet.includes('items.length === 0 || !plan.draft?.plan_digest'), 'empty proposals must not be applicable')
assert(sheet.includes('技能版本'), 'proposal must show skill version')
assert(sheet.includes('校验提醒'), 'preview warnings must be visible')
assert(hook.includes('management_plan_non_simplified_chinese'), 'language error must have a stable Chinese UI message')
assert(hook.includes('请重新校验或重新生成'), 'stale plans must show an actionable next step')
assert(history.includes('草案请在首页 AI 管理方案窗口中审阅'), 'history empty state must explain the draft boundary')
assert(app.includes('const [mindmapReturnContext, setMindmapReturnContext]'), 'app must retain the reward return context after navigation')
assert(app.includes('const handleMindmapNavigate = useCallback'), 'app must handle mindmap navigation separately from ordinary tabs')
assert(app.includes('mindmapRewardFingerprint(snapshot, mindmapReturnContext)'), 'app must compare only the selected reward fingerprint')
assert(app.includes("setManagementPlanMode('history')"), 'a changed reward snapshot must reopen history mode')
assert(app.includes('if (fingerprint === mindmapReturnContext.fingerprint) return'), 'unchanged snapshots, including cancel or failed saves, must not return')
assert(app.includes('onNavigate={handleMindmapNavigate}'), 'management plan sheet must use the return-aware navigation handler')

console.log('management plan history contracts passed')
