package com.mytimelogger.app;

import static org.junit.Assert.*;
import java.net.SocketTimeoutException;
import java.util.*;
import org.junit.Test;

public class WidgetTimerApiClientTest {
    private static final String STOPPED="{\"status\":\"stopped\",\"state\":null}";
    private static String state(String status,String state,long revision,long category){return "{\"status\":\""+status+"\",\"state\":{"+
            "\"session_id\":\"s1\",\"revision\":"+revision+",\"state\":\""+state+"\",\"active\":"+(!"stopped".equals(state))+",\"category_id\":"+category+",\"category_name\":\"状态切换\",\"started_at\":\"2026-08-24 10:00:00+08:00\",\"segment_started_at\":\"2026-08-24 10:00:00+08:00\",\"active_elapsed_ms\":1000,\"timer_mode\":\"countup\",\"duration_ms\":0,\"pause_count\":0,\"server_time\":\"2026-08-24 10:00:01+08:00\"}}";}
    private static WidgetTimerRuntimeStore.Config runtime(){return new WidgetTimerRuntimeStore.Config("https://example.test","test-token","d1","u1",1);}
    private static WidgetTimerCommand command(String action,String id,long category){Map<String,Object> raw=new HashMap<>();raw.put("action",action);raw.put("commandId",id);raw.put("categoryId",category);raw.put("eventEpochMs",1L);return WidgetTimerCommand.parse(raw);}
    private static final class Fake implements WidgetTimerApiClient.Transport {
        final Queue<Object> replies=new ArrayDeque<>(); final List<String> calls=new ArrayList<>(); final List<Map<String,String>> headers=new ArrayList<>(); final List<String> bodies=new ArrayList<>();
        public WidgetTimerApiClient.Response request(String method,String url,Map<String,String> header,String body,int timeout)throws Exception{calls.add(method+" "+url);headers.add(header);bodies.add(body);Object next=replies.remove();if(next instanceof Exception)throw (Exception)next;return (WidgetTimerApiClient.Response)next;}
    }
    @Test public void startsAndSwitchesStatusCategoryWithRequiredHeaders(){
        Fake fake=new Fake();fake.replies.add(new WidgetTimerApiClient.Response(200,STOPPED));fake.replies.add(new WidgetTimerApiClient.Response(200,state("accepted","running",1,7)));
        assertTrue(new WidgetTimerApiClient(fake,System::currentTimeMillis,8000).execute(runtime(),command("start","c1",7),"状态切换").applied());
        assertTrue(fake.calls.get(1).endsWith("/start"));assertEquals("Bearer test-token",fake.headers.get(0).get("Authorization"));assertEquals("timer-current-state-v1",fake.headers.get(0).get("X-MTL-Timer-State"));assertTrue(fake.bodies.get(1).contains("\"timer_mode\":\"countup\""));
        Fake switching=new Fake();switching.replies.add(new WidgetTimerApiClient.Response(200,state("active","running",2,5)));switching.replies.add(new WidgetTimerApiClient.Response(200,state("accepted","running",3,7)));
        assertTrue(new WidgetTimerApiClient(switching,System::currentTimeMillis,8000).execute(runtime(),command("switch","c2",7),"状态切换").applied());assertTrue(switching.calls.get(1).endsWith("/switch"));
    }
    @Test public void sameCategoryStartDoesNotPostAndMismatchedStopPosts(){Fake same=new Fake();same.replies.add(new WidgetTimerApiClient.Response(200,state("active","running",2,7)));assertTrue(new WidgetTimerApiClient(same,System::currentTimeMillis,8000).execute(runtime(),command("start","same",7),"运动").applied());assertEquals(1,same.calls.size());Fake stop=new Fake();stop.replies.add(new WidgetTimerApiClient.Response(200,state("active","running",2,8)));stop.replies.add(new WidgetTimerApiClient.Response(200,state("accepted","stopped",3,8)));assertTrue(new WidgetTimerApiClient(stop,System::currentTimeMillis,8000).execute(runtime(),command("stop","stop",7),"运动").applied());assertEquals(2,stop.calls.size());assertTrue(stop.calls.get(1).endsWith("/stop"));}
    @Test public void staleRetriesOnceWithStableIntentAndAttemptKeys(){Fake fake=new Fake();fake.replies.add(new WidgetTimerApiClient.Response(200,state("active","running",2,5)));fake.replies.add(new WidgetTimerApiClient.Response(200,"{\"status\":\"conflict\",\"error_code\":\"stale_timer_revision\",\"state\":"+state("active","running",3,6).substring(state("active","running",3,6).indexOf("{",1),state("active","running",3,6).length()-1)+"}"));fake.replies.add(new WidgetTimerApiClient.Response(200,state("accepted","running",4,7)));assertTrue(new WidgetTimerApiClient(fake,System::currentTimeMillis,8000).execute(runtime(),command("switch","stable",7),"运动").applied());assertEquals(3,fake.calls.size());assertTrue(fake.bodies.get(1).contains("\"idempotency_key\":\"stable:1\""));assertTrue(fake.bodies.get(2).contains("\"idempotency_key\":\"stable:2\""));assertTrue(fake.bodies.get(1).contains("\"user_intent_id\":\"stable\""));assertTrue(fake.bodies.get(2).contains("\"user_intent_id\":\"stable\""));}
    @Test public void reportsAuthNetworkAndTimeoutWithoutApplied(){Fake auth=new Fake();auth.replies.add(new WidgetTimerApiClient.Response(401,"{}"));assertEquals("unauthorized",new WidgetTimerApiClient(auth,System::currentTimeMillis,8000).execute(runtime(),command("start","a",7),"运动").status);Fake offline=new Fake();offline.replies.add(new java.io.IOException());assertEquals("network",new WidgetTimerApiClient(offline,System::currentTimeMillis,8000).execute(runtime(),command("start","b",7),"运动").status);Fake timeout=new Fake();timeout.replies.add(new SocketTimeoutException());assertEquals("timeout",new WidgetTimerApiClient(timeout,System::currentTimeMillis,1).execute(runtime(),command("start","c",7),"运动").status);}
    @Test public void readCurrentStateIsGetOnlyAndRejectsAuthOfflineAndInvalidPayload(){Fake ok=new Fake();ok.replies.add(new WidgetTimerApiClient.Response(200,state("active","running",2,7)));WidgetTimerApiClient.Outcome outcome=new WidgetTimerApiClient(ok,System::currentTimeMillis,8000).readCurrentState(runtime());assertTrue(outcome.applied());assertEquals(Collections.singletonList("GET https://example.test/api/timer/current"),ok.calls);assertNull(ok.bodies.get(0));Fake auth=new Fake();auth.replies.add(new WidgetTimerApiClient.Response(403,"{}"));assertEquals("unauthorized",new WidgetTimerApiClient(auth,System::currentTimeMillis,8000).readCurrentState(runtime()).status);Fake offline=new Fake();offline.replies.add(new java.io.IOException());assertEquals("network",new WidgetTimerApiClient(offline,System::currentTimeMillis,8000).readCurrentState(runtime()).status);Fake invalid=new Fake();invalid.replies.add(new WidgetTimerApiClient.Response(200,"{}"));assertEquals("failed",new WidgetTimerApiClient(invalid,System::currentTimeMillis,8000).readCurrentState(runtime()).status);}
    @Test public void duplicateIntentKeepsOneBusinessKeyAndLateAcceptedIsNotApplied(){Fake replay=new Fake();for(int i=0;i<2;i++){replay.replies.add(new WidgetTimerApiClient.Response(200,STOPPED));replay.replies.add(new WidgetTimerApiClient.Response(200,state("accepted","running",1,7)));}WidgetTimerApiClient client=new WidgetTimerApiClient(replay,System::currentTimeMillis,8000);assertTrue(client.execute(runtime(),command("start","same-id",7),"运动").applied());assertTrue(client.execute(runtime(),command("start","same-id",7),"运动").applied());assertEquals(replay.bodies.get(1),replay.bodies.get(3));long[] now={0};WidgetTimerApiClient.Transport late=(method,url,headers,body,timeout)->{if("POST".equals(method))now[0]=9000;return new WidgetTimerApiClient.Response(200,"POST".equals(method)?state("accepted","running",1,7):STOPPED);};assertEquals("timeout",new WidgetTimerApiClient(late,()->now[0],8000).execute(runtime(),command("start","late",7),"运动").status);}
}
