# -*- coding: utf-8 -*-
import importlib.util
from pathlib import Path


MODULE_PATH = Path(__file__).resolve().parents[2] / "server" / "skills" / "time-management" / "generate_full_report.py"
SKILL_PATH = Path(__file__).resolve().parents[2] / "server" / "skills" / "time-management" / "SKILL.md"
spec = importlib.util.spec_from_file_location("generate_full_report_for_test", MODULE_PATH)
report_module = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(report_module)


def test_v4_sleep_settlement_report_uses_eight_snapshot_dimensions_and_deep_penalty():
    dimensions = {
        "sleep_cycles": {"reason": "睡眠周期", "raw_value": 5.5, "matched_rule": ">=5.5", "score": 30, "max_score": 30},
        "on_time_sleep": {"reason": "按时入睡", "raw_value": "23:00", "matched_rule": "22:30–23:30", "score": 20, "max_score": 20},
        "wake_up": {"reason": "起床用时", "raw_value": 20, "matched_rule": "<=20分钟", "score": 15, "max_score": 15},
        "awake_count": {"reason": "清醒次数", "raw_value": 0, "matched_rule": "0次", "score": 10, "max_score": 10},
        "deep_sleep": {"reason": "深睡时长", "raw_value": 59, "matched_rule": "<60分钟", "score": 0, "max_score": 10},
        "report_before_nine": {"reason": "9点前生成睡眠报告", "raw_value": "08:00", "matched_rule": "09:00前已生成", "score": 5, "max_score": 5},
        "huawei_sleep_score": {"reason": "华为睡眠评分", "raw_value": 90, "matched_rule": ">=85", "score": 5, "max_score": 5},
        "awake_duration": {"reason": "清醒时长", "raw_value": 0, "matched_rule": "0分钟", "score": 5, "max_score": 5},
    }
    content = "\n".join(report_module.build_sleep_settlement_lines({
        "status": "scored", "rule_version": "sleep-score-v4", "dimensions": dimensions, "score_total": 90,
        "reward_amount": 80, "cycle_penalty": 0, "deep_sleep_penalty": -20, "completion_reward_amount": 0,
        "completion_reason": "存在未满分睡眠指标", "net_amount": 60, "report_completed_at": "2026-09-12 08:00:00",
        "ledger_sources": {"deep_sleep_penalty": "sleep-score:2026-09-12:sleep-score-v4:deep-sleep-penalty"},
    }))
    assert "**总分**：90/100" in content and "深睡时长不足（<60分钟）惩罚**：-20 🪙" in content
    assert content.count("影响睡眠评分奖励；本项无独立金币流水") == 8
    assert "入睡用时" not in content and "起床规律" not in content
    assert content.index("睡眠周期") < content.index("按时入睡") < content.index("起床用时")


def test_sleep_report_format_contains_trends_and_rich_ai(tmp_path, monkeypatch):
    monkeypatch.setattr(report_module, "resolve_reports_dir", lambda: tmp_path)
    data = {
        "sleep": {
            "date": "2026-05-26",
            "sleep_score": 83,
            "total_sleep_min": 392,
            "sleep_cycles": 4.36,
            "deep_sleep_min": 106,
            "light_sleep_min": 209,
            "rem_sleep_min": 77,
            "fall_asleep_min": 6,
            "wake_up_min": 5,
            "awake_count": 2,
            "awake_min": 7,
            "deep_sleep_ratio": 27,
            "sleep_start": "01:26",
            "sleep_end": "08:05",
            "atm_sleep_start": "01:20",
            "atm_sleep_end": "08:10",
            "extracted_by": "test-model",
            "official_advice": "官方建议：保持规律作息，睡前减少屏幕刺激。",
            "morning_diary": "早上精神不错，准备轻量启动。",
            "calc_trace": ["1. 睡眠周期: 392min / 90 = 4.36个"],
        },
        "history_7day": [
            {"date": "2026-05-25", "sleep_score": 76, "total_sleep_min": 343, "sleep_cycles": 3.81, "fall_asleep_min": 102, "wake_up_min": 6, "deep_sleep_ratio": 22, "awake_count": 2},
            {"date": "2026-05-26", "sleep_score": 83, "total_sleep_min": 392, "sleep_cycles": 4.36, "fall_asleep_min": 6, "wake_up_min": 5, "deep_sleep_ratio": 27, "awake_count": 2},
        ],
        "summary": {"activity_breakdown": {"睡觉": 24600, "松鼠病": 14520, "车": 2520}},
        "atimelogger": {"activities": []},
    }
    analysis = report_module.ensure_rich_analysis({
        "efficiency_score": 80,
        "summary": "今天表现不错，继续保持！",
        "insights": [],
        "recommendations": [],
        "issues": [],
    }, data)

    path = Path(report_module.generate_full_report_file(data, analysis, "2026-05-26", include_time_analysis=False))
    content = path.read_text(encoding="utf-8")

    assert "# 📔 深度复盘报告 - 2026-05-26" in content
    assert "## 📈 [复盘摘要]" not in content
    assert "效率评分" not in content
    assert "今日总结" not in content
    assert "Generated by MyTimeLogger v4.2" not in content
    assert "### 1.2 最近 7 天睡眠变化趋势" in content
    assert "### 1.3 关键指标变化解读" in content
    assert "### 1.5 AI 睡眠解读" in content
    assert "### 1.6 晨间日记" in content
    assert "### 1.5 晨间日记" not in content
    assert "### 🎯 睡眠行动建议" in content
    assert content.index("### 🎯 睡眠行动建议") < content.index("### 1.6 晨间日记")
    assert "早上精神不错，准备轻量启动。" in content
    assert "上一次" in content and "当前" in content
    assert "官方建议：保持规律作息，睡前减少屏幕刺激。" in content
    assert "睡眠质量" not in content
    assert "2026年" not in content
    assert content.count("- ") >= 10
    assert "## ⏱️ [Part 2: 时间管理报告]" not in content
    assert "每天至少要完成 5 个睡眠周期" in content
    assert "清醒时长" in content and "清醒次数" in content
    assert "## 💡 [AI 深度洞察]" not in content
    assert "晨间日记奖励" in content and "晚间日记奖励" in content
    assert "双日记" not in content
    assert "quick-report" not in content


def test_full_report_contains_part_two(tmp_path, monkeypatch):
    monkeypatch.setattr(report_module, "resolve_reports_dir", lambda: tmp_path)
    data = {
        "sleep": {"sleep_score": 80, "total_sleep_min": 420, "sleep_cycles": 4.67, "official_advice": "测试官方建议。", "evening_diary": "今天晚上复盘。", "calc_trace": []},
        "history_7day": [],
        "summary": {"activity_breakdown": {"睡觉": 25200, "输入": 3600, "输出": 1800, "副业生产": 2400, "娱乐": 1200, "松鼠病": 1800}},
        "atimelogger": {"activities": []},
    }
    analysis = report_module.ensure_rich_analysis({"efficiency_score": 80, "summary": "ok"}, data)
    path = Path(report_module.generate_full_report_file(data, analysis, "2026-05-26", include_time_analysis=True))
    content = path.read_text(encoding="utf-8")
    assert "## ⏱️ [Part 2: 时间管理报告]" in content
    assert content.index("### 1.5 AI 睡眠解读") < content.index("### 1.6 晨间日记")
    assert content.index("### 1.6 晨间日记") < content.index("## ⏱️ [Part 2: 时间管理报告]")
    assert content.index("### 2.3 AI 时间管理解读") < content.index("### 2.7 晚间日记")
    assert "今天晚上复盘。" in content
    assert "自我提升" in content
    assert "经济价值" in content
    assert "消耗性投入" in content
    assert "---\n\n## ⏱️ [Part 2: 时间管理报告]" in content
    assert "## 💡 [AI 深度洞察]" not in content
    assert "Generated by MyTimeLogger v4.2" not in content


def test_sleep_cycles_193_gets_severe_warning(tmp_path, monkeypatch):
    monkeypatch.setattr(report_module, "resolve_reports_dir", lambda: tmp_path)
    data = {
        "sleep": {
            "sleep_score": 60,
            "total_sleep_min": 174,
            "sleep_cycles": 1.93,
            "fall_asleep_min": 86,
            "wake_up_min": 31,
            "awake_min": 163,
            "awake_count": 4,
            "official_advice": "测试官方建议。",
            "calc_trace": [],
        },
        "history_7day": [
            {"date": "2026-06-29", "sleep_score": 70, "total_sleep_min": 360, "sleep_cycles": 4.0, "fall_asleep_min": 40, "wake_up_min": 20, "awake_min": 20, "awake_count": 2},
            {"date": "2026-06-30", "sleep_score": 60, "total_sleep_min": 174, "sleep_cycles": 1.93, "fall_asleep_min": 86, "wake_up_min": 31, "awake_min": 163, "awake_count": 4},
        ],
        "summary": {"activity_breakdown": {"睡觉": 10440, "娱乐": 7200, "松鼠病": 3600}},
        "atimelogger": {"activities": []},
    }
    analysis = report_module.ensure_rich_analysis({"efficiency_score": 40, "summary": "bad"}, data)
    path = Path(report_module.generate_full_report_file(data, analysis, "2026-06-30", include_time_analysis=False))
    content = path.read_text(encoding="utf-8")
    assert "1.93 个" in content or "1.93个" in content
    assert "严重不足" in content
    assert "严重预警" in content
    assert "恢复窗口已经被明显压缩" in content


def test_sleep_skill_prompt_requires_strict_coaching_rules():
    content = SKILL_PATH.read_text(encoding="utf-8")
    assert "禁止输出 `Generated by MyTimeLogger v4.2`" in content
    assert "每天睡眠周期目标为至少 5 个" in content
    assert "睡眠周期、总睡眠、睡眠评分、入睡时长、起床时长、清醒时长、清醒次数是重点指标" in content
    assert "严厉批评、问题总结、可能行为原因和当天纠偏动作" in content
    assert "15 个分类" in content
    assert "副业生产、副业营销、副业研发" in content
    assert "刺痛、羞耻提醒式语气" in content
    assert "睡眠周期 <3 时必须使用骂醒式严重警示" in content
    assert "晨间日记必须属于 Part 1，位于 Part 1 最后" in content
